#!/usr/bin/env bash
RUNNER="supervised_5cv"
EXPERIMENT_NAME="sgmet_e2e_scratch_semantic_2cls_outmargin_m90_lam0p5_fd10_cd90"
DATE_TAG="${DATE_TAG:-$(date +%Y%m%d)}"

# Output cosine margin: penalize summary-vector cosine similarity only above 0.90.
EXPERT_INIT="random"
TRAIN_EXPERTS=1
CLUSTER_CSV_NAME="feature_clusters_biolord_v4_k8_leiden.csv"
NUM_SUMMARY_TOKENS=2
SUMMARY_DIAGNOSTICS=1

SUMMARY_AUX_LOSS="output_margin"
SUMMARY_AUX_WEIGHT="${SUMMARY_AUX_WEIGHT:-0.5}"
SUMMARY_AUX_WARMUP_EPOCHS="${SUMMARY_AUX_WARMUP_EPOCHS:-5}"
SUMMARY_ATTENTION_MARGIN="0.90"
SUMMARY_OUTPUT_MARGIN="${SUMMARY_OUTPUT_MARGIN:-0.90}"
SUMMARY_MI_BETA="1.0"
SUMMARY_MI_TEMPERATURE="1.0"

EPOCHS="${EPOCHS:-80}"
LR="${LR:-8e-4}"
EXPERT_LR="${EXPERT_LR:-8e-4}"
WEIGHT_DECAY="${WEIGHT_DECAY:-5e-4}"
FEATURE_DROPOUT_PROB_MAX="${FEATURE_DROPOUT_PROB_MAX:-0.10}"
CLUSTER_DROPOUT_PROB_MAX="${CLUSTER_DROPOUT_PROB_MAX:-0.90}"
